add npm publish step

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -4,6 +4,8 @@ on:
   push:
     branches:
       - master
+    tags:
+      - '*'
 
 jobs:
   docker:
@@ -11,16 +13,39 @@ jobs:
 
     steps:
       - uses: actions/checkout@v2
-      - name: Set up Docker Buildx
+
+      - name: Compute Tags
+        id: compute_tags
+        run: |
+          branch="${GITHUB_REF#refs/heads/}"
+          tag="${GITHUB_REF#refs/tags/v}"
+          if [ "$branch" != "$GITHUB_REF" ]; then
+            branch="$(echo "$branch" | sed -e 's/[^a-zA-Z0-9\-\.]/-/g')"
+            echo "::set-output name=TAGS::boxboat/dockhand-lite:commit-${branch}"
+          elif [ "$tag" != "$GITHUB_REF" ]; then
+            latest=""
+            if ! echo "$tag" | grep -qF '-'; then
+              latest=",boxboat/dockhand-lite:latest"
+            fi
+            tag="$(echo "$tag" | sed -e 's/[^a-zA-Z0-9\-\.]/-/g')"
+            echo "::set-output name=TAGS::boxboat/dockhand-lite:${tag}${latest}"
+          else
+            echo "unable to determine tag" >&2
+            exit 1
+          fi
+
+      - name: Setup Docker Buildx
         uses: docker/setup-buildx-action@v1
+
       - name: Login to DockerHub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
+
       - name: Build and push
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           push: true
-          tags: boxboat/dockhand-lite:latest
+          tags: "${{ steps.compute_tags.outputs.TAGS }}"
